### ISSUE TITLE
Please add default tags in main.tf

### ISSUE THREAD

**Issue by raguvaran-madhiyan** [traveloka/terraform-aws-privatelink-provider#3]
Our ECI multi account supports many different services , its better if we have tags in place

tags = {
    Description   = "${var.description}"
    Environment   = "${var.environment}"
    ManagedBy     = "Terraform"
    Name          = "${module.service-provider.service_provider_name}"
    ProductDomain = "${var.product_domain}"
    Service       = "${var.service_name}"
    Project = ${var.project_name}
}

**Comment by febryantonius** [comment]
Resolved in #5
